server:
  port: 8081

# 数据库配置
spring:
 #数据源
  datasource:
    url: jdbc:mysql://hnm-sqldb.csang7vsleyt.us-west-2.rds.amazonaws.com:3306/devshop?useSSL=false&useUnicode=true&characterEncoding=utf-8&allowMultiQueries=true
    username: hnmmaster
    password: hg9NfM24jx001
    driver-class-name: com.mysql.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      filters: stat
      maxActive: 20
      initialSize:  10
      maxWait: 60000
      minIdle: 10
      timeBetweenEvictionRunsMillis: 60000
      minEvictableIdleTimeMillis: 300000
      validationQuery: select 'x'
      testWhileIdle: true
      testOnBorrow: false
      testOnReturn: false
      poolPreparedStatements: true
      maxOpenPreparedStatements: 20
      stat-view-servlet:
        login-username: admin
        login-password: admin
        url-pattern: /druid/*

  #redis
  redis:
    host: 127.0.0.1
    port: 6379
    timeout: 10000
    pool:
     # 连接池最大连接数（使用负值表示没有限制）
      max-active: 20
      # 连接池最大阻塞等待时间（使用负值表示没有限制）
      max-wait: 5000
      # 连接池中的最大空闲连接
      max-idle: 20
      # 连接池中的最小空闲连接
      min-idle: 5


logging:
  level: DEBUG

#  redis:
#      host: 192.168.145.132
#      port: 6379
#      timeout: 20000
#      cluster:
#          nodes: 192.168.211.134:7000,192.168.211.134:7001,192.168.211.134:7002
#          maxRedirects: 6
#      pool:
#          max-active: 8
#          min-idle: 0
#          max-idle: 8
#          max-wait: -1
